name: cosmic-development-linux
channels:
- conda-forge
dependencies:
- certifi=2019.6.16=py36_0
- cycler=0.10.0=py36_0
- docutils=0.15=py36_0
- importlib_metadata=0.17=py36_1
- ligo-common=1.0.3=py_0
- ligo-segments=1.2.0=py36h14c3975_0
- pip=19.1.1=py36_0
- pluggy=0.12.0=py_0
- pyparsing=2.4.0=py_0
- pytest=5.0.1=py36_0
- pytz=2019.1=py_0
- setuptools=41.0.1=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.33.4=py36_0
- zipp=0.5.1=py_0
- _libgcc_mutex=0.1=main
- astropy=3.2.1=py36h7b6447c_0
- atomicwrites=1.3.0=py36_1
- attrs=19.1.0=py36_1
- blas=1.0=mkl
- ca-certificates=2019.5.15=0
- cloog=0.18.0=0
- dbus=1.13.6=h746ee38_0
- expat=2.2.6=he6710b0_0
- fontconfig=2.13.0=h9420a91_0
- freetype=2.9.1=h8a8886c_1
- gcc=4.8.5=7
- glib=2.56.2=hd408876_0
- gmp=6.1.2=h6c8ec71_1
- gst-plugins-base=1.14.0=hbbd80ab_1
- gstreamer=1.14.0=hb453b48_1
- h5py=2.9.0=py36h7918eee_0
- hdf5=1.10.4=hb1b8bf9_0
- icu=58.2=h9c2bf20_1
- intel-openmp=2019.4=243
- isl=0.12.2=0
- jpeg=9b=h024ee3a_2
- kiwisolver=1.1.0=py36he6710b0_0
- libedit=3.1.20181209=hc058e9b_0
- libffi=3.2.1=hd88cf55_4
- libgcc-ng=9.1.0=hdf63c60_0
- libgfortran-ng=7.3.0=hdf63c60_0
- libpng=1.6.37=hbc83047_0
- libstdcxx-ng=9.1.0=hdf63c60_0
- libuuid=1.0.3=h1bed415_2
- libxcb=1.13=h1bed415_1
- libxml2=2.9.9=hea5a465_1
- matplotlib=3.1.0=py36h5429711_0
- mkl=2019.4=243
- mkl-service=2.0.2=py36h7b6447c_0
- mkl_fft=1.0.12=py36ha843d7b_0
- mkl_random=1.0.2=py36hd81dba3_0
- more-itertools=7.0.0=py36_0
- mpc=1.0.3=hec55b23_5
- mpfr=3.1.5=h11a74b3_2
- ncurses=6.1=he6710b0_1
- numpy=1.16.4=py36h7e9f1db_0
- numpy-base=1.16.4=py36hde5b4d6_0
- openssl=1.1.1c=h7b6447c_1
- packaging=19.0=py36_0
- pandas=0.24.2=py36he6710b0_0
- pcre=8.43=he6710b0_0
- psutil=5.6.3=py36h7b6447c_0
- py=1.8.0=py36_0
- pyqt=5.9.2=py36h05f1152_2
- pytest-arraydiff=0.3=py36h39e3cac_0
- pytest-astropy=0.5.0=py36_0
- pytest-doctestplus=0.3.0=py36_0
- pytest-openfiles=0.3.2=py36_0
- pytest-remotedata=0.3.1=py36_0
- python=3.6.8=h0371630_0
- python-dateutil=2.8.0=py36_0
- qt=5.9.7=h5867ecd_1
- readline=7.0=h7b6447c_5
- scipy=1.3.0=py36h7c811a0_0
- sip=4.19.8=py36hf484d3e_0
- six=1.12.0=py36_0
- sqlite=3.29.0=h7b6447c_0
- tk=8.6.8=hbc83047_0
- tornado=6.0.3=py36h7b6447c_0
- xz=5.2.4=h14c3975_4
- zlib=1.2.11=h7b6447c_3
prefix: /projects/b1095/ligo_software/envs/cosmic-development-linux
