name: cosmic-development
channels:
  - defaults
  - conda-forge
dependencies:
  - alabaster=0.7.12=py_0
  - asn1crypto=0.24.0=py37_1003
  - astropy=3.2.1=py37h01d97ff_0
  - atomicwrites=1.3.0=py_0
  - attrs=19.1.0=py_0
  - babel=2.7.0=py_0
  - bzip2=1.0.6=h1de35cc_1002
  - ca-certificates=2019.6.16=hecc5488_0
  - certifi=2019.6.16=py37_0
  - cffi=1.12.3=py37hccf1714_0
  - chardet=3.0.4=py37_1003
  - cloog=0.18.0=10
  - cryptography=2.7=py37h212c5bf_0
  - cycler=0.10.0=py_1
  - docutils=0.14=py37_1001
  - dqsegdb2=1.0.1=py_0
  - freetype=2.10.0=h24853df_0
  - gcc=4.8.5=8
  - gmp=5.1.2=6
  - gwdatafind=1.0.4=py_0
  - gwosc=0.4.3=py_0
  - gwpy=0.15.0=py37_0
  - h5py=2.9.0=nompi_py37h35dc34b_1102
  - hdf5=1.10.4=nompi_h0cbb7df_1106
  - idna=2.8=py37_1000
  - imagesize=1.1.0=py_0
  - importlib_metadata=0.18=py37_0
  - isl=0.12.2=1
  - jinja2=2.10.1=py_0
  - kiwisolver=1.1.0=py37h770b8ee_0
  - libblas=3.8.0=10_openblas
  - libcblas=3.8.0=10_openblas
  - libcxx=8.0.0=4
  - libcxxabi=8.0.0=4
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=3.0.1=0
  - liblapack=3.8.0=10_openblas
  - libopenblas=0.3.6=hd44dcd8_4
  - libpng=1.6.37=h2573ce8_0
  - ligo-common=1.0.3=py_0
  - ligo-segments=1.2.0=py37h1de35cc_0
  - ligotimegps=2.0.1=py_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.1=py37_0
  - matplotlib-base=3.1.1=py37h3a684a6_0
  - more-itertools=7.1.0=py_0
  - mpc=1.1.0=5
  - mpfr=4.0.1=0
  - ncurses=6.1=h0a44026_1002
  - numpy=1.16.4=py37h6b0580a_0
  - openblas=0.3.6=hd44dcd8_4
  - openssl=1.1.1b=h01d97ff_2
  - packaging=19.0=py_0
  - pandas=0.24.2=py37h86efe34_0
  - pip=19.1.1=py37_0
  - pluggy=0.12.0=py_0
  - psutil=5.6.3=py37h01d97ff_0
  - py=1.8.0=py_0
  - pycparser=2.19=py37_1
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pysocks=1.7.0=py37_0
  - pytest=5.0.1=py37_0
  - pytest-arraydiff=0.3=py_0
  - pytest-astropy=0.5.0=py_0
  - pytest-doctestplus=0.3.0=py_0
  - pytest-openfiles=0.3.1=py_0
  - pytest-remotedata=0.3.1=py_0
  - python=3.7.3=h93065d6_1
  - python-dateutil=2.8.0=py_0
  - pytz=2019.1=py_0
  - readline=8.0=hcfe32e1_0
  - requests=2.22.0=py37_0
  - scipy=1.3.0=py37hab3da7d_0
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_1000
  - snowballstemmer=1.9.0=py_0
  - sphinx=2.1.2=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.1=py_0
  - sqlite=3.28.0=hb7d70f7_1
  - tk=8.6.9=h2573ce8_1002
  - tornado=6.0.3=py37h01d97ff_0
  - tqdm=4.32.2=py_0
  - urllib3=1.24.3=py37_0
  - wcwidth=0.1.7=py_1
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h1de35cc_1001
  - zipp=0.5.1=py_0
  - zlib=1.2.11=h1de35cc_1004
prefix: /Users/scottcoughlin/anaconda/envs/cosmic-development

